"""borrowed table and relation to authorbook table

Revision ID: 120fac30b454
Revises: c35c32d7bf43
Create Date: 2020-08-02 15:13:09.356624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120fac30b454'
down_revision = 'c35c32d7bf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('authorbook_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorbook_id'], ['author_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowed')
    # ### end Alembic commands ###
